name: Build specific CPP file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # 自定义 CMake 构建类型 (Release, Debug, RelWithDebInfo, 等等)
  BUILD_TYPE: Release

jobs:
  build:
    # CMake 配置和构建命令是平台无关的，应该在 Windows 或 Mac 上同样有效。
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # 在 'build' 子目录中配置 CMake。`CMAKE_BUILD_TYPE` 仅在使用单配置生成器（如 make）时才需要。
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build specific CPP file
      # 编译特定的 CPP 文件
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target your_specific_target_name
